services:
  influxdb:
    image: influxdb:1.8
    #ports:
    #  - "8086:8086"
    network_mode: host
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:9.3.8
    #ports:
    #  - "3000:3000"
    network_mode: host
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  k6:
    container_name: k6_runner
    image: grafana/k6:latest
    #ports:
    #  - "6565:6565"
    network_mode: host
    environment:
      - K6_OUT=influxdb=http://localhost:8086/k6
    volumes:
      - ./scripts:/scripts
